kappazunder bildstandorte vom stadt wien wfs server laden und als points.gpkg ablegen

In [ ]:
import geopandas as gpd

points = gpd.read_file("points.gpkg", layer="kappazunder_image_punkte")
points.head()

,objectid,losid,trajectoryid,epoch,image_name,lat,lon,geometry
0,4036820.0,9,15419,2020-05-19 06:21:10+00:00,WE1G6DY7.jpg,48.172907,16.324055,POINT (-601.117 337164.375)
1,4036821.0,9,15419,2020-05-19 06:21:10.100000+00:00,WE1G6DY8.jpg,48.172901,16.324015,POINT (-604.045 337163.728)
2,4036822.0,9,15419,2020-05-19 06:21:11+00:00,WE1G6DY9.jpg,48.172895,16.323976,POINT (-606.968 337163.059)
3,4036823.0,9,15419,2020-05-19 06:21:11.100000+00:00,WE1G6DYA.jpg,48.172889,16.323937,POINT (-609.889 337162.387)
4,4036824.0,9,15419,2020-05-19 06:21:11.200000+00:00,WE1G6DYB.jpg,48.172883,16.323898,POINT (-612.813 337161.732)

In [12]:
import re

def to_snake_case(s):
    s = s.strip()               
    s = s.lower()            
    s = re.sub(r'[ -]+', '_', s)
    s = re.sub(r'[^\w-]', '', s)
    return s

points.columns = [to_snake_case(col) for col in points.columns]

timestamps der datenpunkte haben nur sekundenauflösung.  
für streng monoton steigende timestamps aufeinanderfolgende datenpunkte mit gleichen timestamps in 100ms schritten separieren.

In [13]:
import pandas as pd

points = points.sort_values(['trajectoryid', 'epoch', 'objectid']).reset_index(drop=True)

# Add milliseconds offset within each (trajectoryid, epoch) group
points['ms_offset'] = points.groupby(['trajectoryid', 'epoch']).cumcount() * 100

# Apply offset as timedelta (1 ms per duplicate)
points['epoch'] = points['epoch'] + pd.to_timedelta(points['ms_offset'], unit='ms')

# Drop helper column
points = points.drop(columns='ms_offset')

bildstandorte sind in epsg:31256, später brauchen wir zusätzlich wsg84

In [14]:
points_wsg84 = points.to_crs(epsg=4326)
points["lat"] = points_wsg84.geometry.y
points["lon"] = points_wsg84.geometry.x

trajectoryid als string interpretieren

In [15]:
points['trajectoryid'] = points['trajectoryid'].astype(str).str.replace('.0', '')
print("New trajectoryid dtype:", points['trajectoryid'].dtype)
print("\nSample of trajectoryid values:")
print(points['trajectoryid'].head())

New trajectoryid dtype: object

Sample of trajectoryid values:
0    15419
1    15419
2    15419
3    15419
4    15419
Name: trajectoryid, dtype: object

der geodatenviewer erlaubt maximal 80gb große downloads.

bei guten 20mb pro datenpunkt macht das etwa 3500 datenpunkten pro download.

die günstige vm bei hetzner hat nur 40gb ssd. außerdem muss das heruntergeladene archiv entpackt werden.
ein archiv muss also etwas unter 20gb haben. damit sind wir bei unter 1000 datenpunkten pro download.

die eine trajektorie umfassenden polygone umfassend zu einem gewissen grad auch trajektorie-fremde datenpunkte was den download vergrößert. um auf nummer sicher zu gehen pro download paket maximal 250 datenpunkte.

In [16]:
print(f"{points['trajectoryid'].nunique()} Trajektorien")
print("Datenpunkte pro Trajektorie:")
print(points["trajectoryid"].value_counts())

175 Trajektorien
Datenpunkte pro Trajektorie:
trajectoryid
15728    21114
16442    20582
15433    20311
15419    20106
16653    19793
         ...
17720       56
16101       40
16471       28
15432        3
17096        2
Name: count, Length: 175, dtype: int64

die trajektorien müssen also aufgeteilt werden.

die datenpunkte jeder trajektorie chronologisch sortieren über die objectid und in untertrajektorien mit maximal 250 datenpunkten aufteilen.

In [17]:
from math import ceil
from tqdm import tqdm

original_trajectories_count = points['trajectoryid'].nunique()

records = []
for traj_id, group in tqdm(points.groupby('trajectoryid')):
    group_sorted = group.sort_values('objectid')
    n = len(group_sorted)
    if n == 0:
        continue
    no_of_splits = int(ceil(n / 250))
    base = n // no_of_splits
    remainder = n % no_of_splits
    sizes = [base + 1] * remainder + [base] * (no_of_splits - remainder)
    i = 0
    for split_i, size in enumerate(sizes):
        end = i + size
        part = group_sorted.iloc[i:end].copy()
        part["original_trajectoryid"] = traj_id
        part['trajectoryid'] = f"{traj_id}_{split_i}" if len(sizes) > 1 else traj_id
        records.append(part)
        i = end

points_split = gpd.GeoDataFrame(pd.concat(records, ignore_index=True), crs=points.crs)

print(f"Original trajectories: {original_trajectories_count}")
print(f"Split trajectories: {points_split['trajectoryid'].nunique()}")
print("Counts per split:")
print(points_split['trajectoryid'].value_counts())

100%|██████████| 175/175 [00:01<00:00, 103.54it/s]

Original trajectories: 175
Split trajectories: 5572
Counts per split:
trajectoryid
17775_22    250
17744_8     250
15763_9     250
15763_10    250
15763_11    250
           ...
17720        56
16101        40
16471        28
15432         3
17096         2
Name: count, Length: 5572, dtype: int64

id der gesplitteten trajektorie zurück in das points dataset mappen

In [18]:
split_mapping = points_split[["objectid", "trajectoryid"]].rename(columns={"trajectoryid": "split_trajectoryid"})

points = points.merge(split_mapping, on="objectid", how="left")
points.head()

,objectid,losid,trajectoryid,epoch,image_name,lat,lon,geometry,split_trajectoryid
0,4036820.0,9,15419,2020-05-19 06:21:10+00:00,WE1G6DY7.jpg,48.172907,16.324055,POINT (-601.117 337164.375),15419_0
1,4036821.0,9,15419,2020-05-19 06:21:10.100000+00:00,WE1G6DY8.jpg,48.172901,16.324015,POINT (-604.045 337163.728),15419_0
2,4036822.0,9,15419,2020-05-19 06:21:11+00:00,WE1G6DY9.jpg,48.172895,16.323976,POINT (-606.968 337163.059),15419_0
3,4036823.0,9,15419,2020-05-19 06:21:11.100000+00:00,WE1G6DYA.jpg,48.172889,16.323937,POINT (-609.889 337162.387),15419_0
4,4036824.0,9,15419,2020-05-19 06:21:11.200000+00:00,WE1G6DYB.jpg,48.172883,16.323898,POINT (-612.813 337161.732),15419_0

der geodatenviewer benötigt einen die gewünschten datenpunkte umfassenden polygon.

dazu die datenpunkte jeder trajektorie chronologisch zu einem linestring verbinden und diesen auf 1 meter dicke buffern.

In [19]:
from shapely.geometry import LineString

records = []
for traj_id, group in tqdm(points_split.groupby('trajectoryid')):
    group_sorted = group.sort_values('objectid')
    geoms = list(group_sorted.geometry)
    if len(geoms) == 0:
        continue
    if len(geoms) == 1:
        # single point trajectory -> keep point (buffer will still work)
        line_geom = geoms[0]
    else:
        coords = [(pt.x, pt.y) for pt in geoms]
        line_geom = LineString(coords).simplify(0.1)
    records.append({'trajectoryid': traj_id, 'geometry': line_geom})

# GeoDataFrame of lines (or single-point geometries for 1-point trajectories)
trajectory_lines = gpd.GeoDataFrame(records, crs=points_split.crs)

# Buffer by 0.5 meter (CRS is EPSG:31256 so units are meters)
trajectories = trajectory_lines.copy()
trajectories['geometry'] = trajectories.geometry.buffer(0.5, cap_style=3, join_style=2)

print("Trajectories (lines):", len(trajectory_lines))
print("Buffered geometries:", len(trajectories))

# Optionally inspect first rows
trajectory_lines.head(), trajectories.head()

100%|██████████| 5572/5572 [00:07<00:00, 793.09it/s]

Trajectories (lines): 5572
Buffered geometries: 5572

(  trajectoryid                                           geometry
 0      15419_0  LINESTRING (-601.117 337164.375, -639.231 3371...
 1      15419_1  LINESTRING (-1329.948 337000.717, -1419.927 33...
 2     15419_10  LINESTRING (900.321 337692.387, 919.529 337706...
 3     15419_11  LINESTRING (1143.693 337869.296, 1131.195 3378...
 4     15419_12  LINESTRING (490.105 337524.24, 467.255 337517....,
   trajectoryid                                           geometry
 0      15419_0  POLYGON ((-639.122 337155.512, -674.282 337147...
 1      15419_1  POLYGON ((-1419.803 336976.826, -1434.323 3369...
 2     15419_10  POLYGON ((919.233 337707.16, 933.824 337717.71...
 3     15419_11  POLYGON ((1131.469 337860.605, 1093.734 337836...
 4     15419_12  POLYGON ((467.406 337516.641, 444.565 337509.3...)

aufbereitete datenpunkte und trajektorie-polygone abspeichern.

In [20]:
points.to_file(
    "points.gpkg", driver="GPKG", layer="kappazunder_image_punkte", index=False
)
trajectories.to_file("trajectories.gpkg", driver="GPKG", index=False)